include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - lib/generated_plugin_registrant.dart
    - lib/**.gql.dart
    - lib/**.gql.g.dart
linter:
  rules:
    close_sinks: true
    one_member_abstracts: true
    lines_longer_than_80_chars: false
    lines_longer_than_100_chars: true
