targets:
  $default:
    builders:
      gql_build|schema_builder:
        enabled: true
      gql_build|ast_builder:
        enabled: true
      gql_build|data_builder:
        enabled: true
        options:
          schema: freeway_app|lib/context/shared/infrastructure/conncection/graphql/schema/schema.graphql
      gql_build|var_builder:
        enabled: true
        options:
          schema: freeway_app|lib/context/shared/infrastructure/conncection/graphql/schema/schema.graphql
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: freeway_app|lib/context/shared/infrastructure/conncection/graphql/schema/schema.graphql

      ferry_generator|req_builder:
        enabled: true
        options:
          schema: freeway_app|lib/context/shared/infrastructure/conncection/graphql/schema/schema.graphql
