name: freeway_app
description: Freeway mobile application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  cupertino_icons: ^1.0.2
  file_picker: ^3.0.2
  ferry: ^0.10.3
  gql_http_link: ^0.4.0
  ferry_hive_store: ^0.4.3
  hive_flutter: ^1.0.0
  uuid: ^3.0.4
  get_it: ^7.2.0
  font_awesome_flutter:
    path: ../font_awesome_flutter/

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.1.0
  import_sorter: ^4.6.0
  ferry_generator: ^0.4.3
  build_runner: ^2.0.4
  mockito: ^5.0.10
  faker: ^2.0.0
import_sorter:
  emojis: true
  comments: true
  ignored_files:
    - \*.gql.dart
flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/900.ttf
          weight: 900
        - asset: assets/fonts/rubik/800.ttf
          weight: 800
        - asset: assets/fonts/rubik/700.ttf
          weight: 700
        - asset: assets/fonts/rubik/600.ttf
          weight: 600
        - asset: assets/fonts/rubik/500.ttf
          weight: 500
        - asset: assets/fonts/rubik/400.ttf
          weight: 400
        - asset: assets/fonts/rubik/300.ttf
          weight: 300
